import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./GlobalRedux/Features/counter/provider";
import Navbar2 from "@/Components/Navbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Patwa-Utensils",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="mb-36">
          <Navbar2/>
          </div>
    
        {children} </Providers></body>
    </html>
  );
}
